config/routes.rb
Rails.application.routes.draw do

  get 'policy/index'

  get 'terms/index'

  get 'register/thankyou'

  devise_for :admins

  resources :policy, only: [:index]
  resources :terms, only: [:index]
  resources :home, only: [:index]
  resources :trainers, only: [:index]
  resources :suitup, only: [:index]
  resources :thelab, only: [:index]
  resources :store, only: [:index]
  resources :register, only: [:index, :list, :thankyou]
  resources :testimonials
  resources :subscribers
  get "/register/list" => "register#list"
  get "/admins/sign_out" => "devise/sessions#destroy"
  post "/testimonials" => "testimonials#index"

  root 'home#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :trackable, :timeoutable 
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
end

app/models/rail.rb
class Rail < ActiveRecord::Base
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
	
end

app/controllers/buy_controller.rb
class BuyController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buy_helper.rb
module BuyHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/policy_helper.rb
module PolicyHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/suitup_helper.rb
module SuitupHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/the_lab_helper.rb
module TheLabHelper
end

app/helpers/thelab_helper.rb
module ThelabHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FiDonce</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
 
  <link href='https://fonts.googleapis.com/css?family=Raleway:400,600' rel='stylesheet' type='text/css'>

</head>
<% if current_admin %>
<div class="admin-nav"><p>Welcome Admin</p><p><%= link_to 'Mailing List', register_list_path %></p><p>|</p>
<p><%= link_to 'Sign Out', destroy_admin_session_path, method: :delete %></p>
  
</div>

<% end %>
<body>

<style type="text/css">

@font-face{
  font-family:'Pirulen';
  src:url('<%= asset_path 'pirulen.ttf' %>')format("truetype");
  font-weight:normal;
  font-style:normal
}
@font-face{
  font-family:'Clarendon';
  src:url('<%= asset_path 'clarendon.ttf' %>')format("truetype");
  font-weight:normal;
  font-style:normal
}

</style>

<aside id="sticky-social">
    <ul>
        <li><a href="https://www.facebook.com/FiDonce/" class="entypo-facebook" target="_blank"><span>Facebook</span></a></li>
        <li><a href="https://www.twitter.com//FiDonce_" class="entypo-twitter" target="_blank"><span>Twitter</span></a></li>
    
        <li><a href="https://www.instagram.com/fidonce__/" class="entypo-instagrem" target="_blank"><span>Instagram</span></a></li>
     
    </ul>
</aside>
  <div class="m-nav-front">
    </div>
    
  <div class="m-nav">

    <p><%= link_to '', root_path, :class => 'logo-s'  %></p>
    <p><%= link_to 'REGISTER.', register_index_path, :class => 'btn2'  %></p>
    <p><%= link_to 'TESTIMONIALS.', testimonials_path, :class => 'btn'  %></p><br><br><br><br><br><br><br><br><br>
    <p class="mnav-link"><%= link_to 'STORE.', store_index_path  %></p>
    <p class="mnav-link"><%= link_to 'THE LAB.', thelab_index_path  %></p>
    <p class="mnav-link"><%= link_to 'TRAINERS.', trainers_path  %></p>
    <p class="mnav-link"><%= link_to 'SUIT UP.', suitup_index_path  %></p>
    
    
  </div>


<nav class="nav">
<p class="logo-s"><%= link_to '', root_path %></p>
<p><%= link_to 'SUIT UP.', suitup_index_path  %></p>
<p><%= link_to 'TRAINERS.', trainers_path  %></p>
<p><%= link_to 'THE LAB.', thelab_index_path  %></p>
<p><%= link_to 'STORE.', store_index_path  %></p>

</nav>
<div class="nav-links">
		<p><%= link_to 'REGISTER.', register_index_path, :class => 'btn2'  %></p>
		<p><%= link_to 'TESTIMONIALS.', testimonials_path, :class => 'btn'  %></p>
	</div>


<%= yield %>

<div class="footer">
<p>©2016 PageCloud Inc Privacy Policy Made with AM'I</p>
<p class="ami-logo"></p><br>
<p style="margin-top: 0;">See <u><%= link_to 'Terms&Conditions', terms_index_path %></u> <u><%=link_to 'Privacy Policy', policy_index_path %></u></p>
</div>



</body>
</html>